services:
  - type: web
    name: hisabi-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_HOST
        value: hisabi-db
      - key: DB_DATABASE
        value: hisabi
      - key: DB_USERNAME
        value: hisabi
      - key: DB_PASSWORD
        value: secret
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: hisabi-db
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.mysql
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: secret
      - key: MYSQL_DATABASE
        value: hisabi
      - key: MYSQL_USER
