services:
  - type: web
    name: hisabi-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: oregon  # ✅ Add this (must match the DB region)
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_HOST
        value: hisabi-db
      - key: DB_DATABASE
        value: hisabi
      - key: DB_USERNAME
        value: hisabi
      - key: DB_PASSWORD
        value: secret
      - key: OPENAI_API_KEY
        sync: false

  - type: private_service
    name: hisabi-db
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.mysql
    dockerContext: .
    region: oregon  # ✅ Add this to ensure they’re colocated
    autoDeploy: true
    skipDeployChecks: true  # ✅ Add this to bypass port scan checks
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: secret
      - key: MYSQL_DATABASE
        value: hisabi
      - key: MYSQL_USER
        value: hisabi
      - key: MYSQL_PASSWORD
        value: secret  # ✅ You were missing this line

    disk:
      name: db-data
      mountPath: /var/lib/mysql
      sizeGB: 1

    healthCheckPath: /
