name: Create Project diagram
on:
  workflow_dispatch: {}
  pull_request:
    branches: [ "main" ]
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Repo Visualizer
        uses: githubocto/repo-visualizer@0.9.1
        with:
          excluded_paths: "ignore,.github"
          artifact_name: "my-diagram"
      - name: Get artifact
        uses: actions/download-artifact@v2
        with:
          name: "my-diagram"
          path: "downloads"
